-- MySQL Script generated by MySQL Workbench
-- Mon May 13 20:47:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chronos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chronos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chronos` DEFAULT CHARACTER SET utf8 ;
USE `chronos` ;

-- -----------------------------------------------------
-- Table `chronos`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chronos`.`sala` (
  `id_sala` INT(8) NOT NULL,
  `nome_sala` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chronos`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chronos`.`responsavel` (
  `id_responsavel` INT(8) NOT NULL,
  `nome_resp` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chronos`.`recado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chronos`.`recado` (
  `id_recado` INT(8) NOT NULL,
  `texto` VARCHAR(100) NOT NULL,
  `data_inicio` DATETIME(6) NOT NULL,
  `data_fim` DATETIME(6) NOT NULL,
  `turno_recado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_recado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chronos`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chronos`.`evento` (
  `id_evento` INT(8) NOT NULL,
  `evento` VARCHAR(50) NOT NULL,
  `data` DATETIME(6) NOT NULL,
  `turno` VARCHAR(50) NOT NULL,
  `sala_id_sala` INT(8) NOT NULL,
  `responsavel_id_responsavel` INT(8) NOT NULL,
  `un_matriz` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(20) NOT NULL,
  `modalidade` VARCHAR(90) NOT NULL,
  `recado_id_recado` INT(8) NOT NULL,
  PRIMARY KEY (`id_evento`, `sala_id_sala`, `responsavel_id_responsavel`),
  INDEX `fk_evento_sala_idx` (`sala_id_sala` ASC),
  INDEX `fk_evento_responsavel1_idx` (`responsavel_id_responsavel` ASC),
  INDEX `fk_evento_recado1_idx` (`recado_id_recado` ASC),
  CONSTRAINT `fk_evento_sala`
    FOREIGN KEY (`sala_id_sala`)
    REFERENCES `chronos`.`sala` (`id_sala`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_responsavel1`
    FOREIGN KEY (`responsavel_id_responsavel`)
    REFERENCES `chronos`.`responsavel` (`id_responsavel`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_recado1`
    FOREIGN KEY (`recado_id_recado`)
    REFERENCES `chronos`.`recado` (`id_recado`)
	ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chronos`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chronos`.`login` (
  `id_login` INT(8) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
